theme: jekyll-theme-leap-day
title: Alexandre Huat
description: Hello you! Welcome to my personal website. Feel free to bookmark this to keep an eye on my project updates.
avatar: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAA2aAAAAJDhlZGJkOGQ1LWY0M2EtNDY2NS1hYzZkLTVkNDg5OWQzMWJiZQ.jpg"

author:
  name: Alexandre Huat
  email: "alexandre.huat@gmail.com"
  github: alexandrehuat
  linkedin: alexandre-huat
  telephone: +33695257087

footer-links-active:
  email: true
  github: true
  linkedin: true
  telephone: false

timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
