theme: jekyll-theme-minimal
title: Alexandre Huat
description: Welcome to my personal website! Follow me on GitHub and social networks to keep an eye on my project updates.
avatar: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAA2aAAAAJDhlZGJkOGQ1LWY0M2EtNDY2NS1hYzZkLTVkNDg5OWQzMWJiZQ.jpg"

author:
  name: Alexandre Huat
  email: "alexandre.huat@gmail.com"
  github: alexandrehuat
  linkedin: alexandre-huat
  researchgate: Alexandre_Huat
  telephone: +33695257087

footer-links-active:
  email: true
  github: true
  linkedin: true
  telephone: false

timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-avatar
  - jekyll-sitemap

gem:
  - jekyll-avatar
