remote_theme: pages-themes/dinky@v0.2.0

title: Alexandre Huat
description: Welcome to my professional website. Follow me on GitHub and social networks to keep an eye on my project updates.
avatar: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAA2aAAAAJDhlZGJkOGQ1LWY0M2EtNDY2NS1hYzZkLTVkNDg5OWQzMWJiZQ.jpg
google_analytics: 5527782389

author:
  name: Alexandre Huat
  github: alexandrehuat
  email: alexandre.huat@gmail.com
  phone: +33749365848
  linkedin: alexandre-huat
  researchgate: Alexandre_Huat

timezone: Europe/Paris
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-avatar
  - jekyll-sitemap

gem:
  - jekyll-avatar
